on:
  pull_request:
    branches:
    - master
    
runs-on: ubuntu-18.04

jobs:
  test:
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - name: Run tests
      run: |
        bundle install
        rake
